import Head from 'next/head'
import Link from 'next/link';
import { styled } from '../styles/stitches-theme';

export default function Home() {
  return (
    <div className='layout'>
      <Head>
        <title>Snippets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Login</h1>
        <Link href="/collections">Go to Collections</Link>
      </main>
    </div>
  )
}