version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ./data/redis:/data.redis



